services:
  client: 
    build: 
      context: ./react-client
      dockerfile: dockerfile
    
    image: spotec-client
    container_name: spotec-client

    env_file:
      - ./react-client/.env

    ports:
      - 3000:3000

    depends_on:
      - server

    command: npm run dev

  server:
    build: 
      context: ./express-server
      dockerfile: dockerfile

    image: spotec-server
    container_name: spotec-server

    env_file:
      - /express-server/.env

    ports:
      - 8000:8000
    
    depends_on:
      - database

    command: npm run start

    
  database: 
    image: mysql:9.0
    container_name: spotec-db

    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: songdb
        MYSQL_PASSWORD: root

    ports:
      - 3306:3306