name: deploy server on ec2

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout to source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ankit8424/spotec-server:${{ github.ref_name }}

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: down all the services
        run: docker compose -f server-compose.yml down --rmi all

      - name: pull latest sever image
        run: docker pull ankit8424/spotec-server:${{ github.ref_name }}

      - name: run all the services
        run: docker compose -f server-compose.yml up -d --build

      - name: remove unused images
        run: docker image prune -f
